version: '3.1'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $DATABASE
    networks:
     - botnet
    volumes:
      - ./database/:/var/lib/postgresql
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  redis:
    networks:
      - botnet
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis:/redis
    command: ["redis-server", "/redis/redis.conf"]

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env.dist"
    volumes:
      - .:/src
    depends_on:
      - postgres
      - redis

networks:
  botnet:
    driver: bridge

